# Generated by Django 4.1.1 on 2022-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
